//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coach
    {
        public int CoachId { get; set; }
        public string CoachName { get; set; }
        public string CoachSurname { get; set; }
        public Nullable<System.DateTime> BirthdayDate { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string CoachPhone { get; set; }
        public Nullable<int> TeamId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Team Team { get; set; }
    }
}
