//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace FC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public int GoalId { get; set; }
        [Required]
        public int PlayerId { get; set; }
        [Required]
        public int MatchId { get; set; }
        public Nullable<int> Minute { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }

      /*  public Goal(int matchId, int playerId, int? minute)
        {
            this.MatchId = matchId;
            this.PlayerId = playerId;
            if (minute != null)
            {
                this.Minute = minute;
            }
        }*/
    }
}
