//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace FC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class League
    {
        public League()
        {
            this.Matches = new HashSet<Match>();
        }
    
        public int LeagueId { get; set; }
        [Required]
        public string LeagueName { get; set; }
        public string LeagueDescription { get; set; }
    
        public virtual ICollection<Match> Matches { get; set; }
    }
}
